Header
coderhood-dev/equipo-4 pull request #5
Opened 2020-12-10 21:04 UTC by Braifz

added  signin / signup / footer

2020-12-11 13:56 UTC, tonoezep requested changes

2020-12-11 13:56 UTC, tonoezep commented on .eslintcache
> +[{"/home/braifz/Workplace/ReactJS/coso-v0.2/src/index.js":"1","/home/braifz/Workplace/ReactJS/coso-v0.2/src/components/App.js":"2","/home/braifz/Workplace/ReactJS/coso-v0.2/src/components/Header.jsx"
esto no es que lo sacamos?

2020-12-11 17:24 UTC, Barrod-code commented on .eslintcache
> +[{"/home/braifz/Workplace/ReactJS/coso-v0.2/src/index.js":"1","/home/braifz/Workplace/ReactJS/coso-v0.2/src/components/App.js":"2","/home/braifz/Workplace/ReactJS/coso-v0.2/src/components/Header.jsx"
No debe haber actualizado el repo local después de que lo sacamos.

2020-12-14 12:53 UTC, tonoezep approved these changes

2020-12-20 23:45 UTC, Barrod-code approved these changes

2020-12-20 23:46 UTC, merged